#!/usr/bin/env bash

# Randomly select a verse from the bible (line-based)
function random_verse() {
  LINE_COUNT=$(wc -l < "$BIBLE")
  LINE=$((RANDOM % LINE_COUNT))
  head -n "$LINE" < "$BIBLE" | tail -n 1
  exit 0
}

# Not sure what issues this might have for non-alphanumerical/colon characters,
# since it would be interpreted as a regex, but they shouldn't appear
# in any references
function named_verse() {
  MATCH=$(echo -e "$1\t")
  VERSE=$(grep "^$MATCH" < "$BIBLE")
  if [ -z "$VERSE" ]; then
    echo "Verse not found"
    exit 1
  else
    echo "$VERSE"
    exit 0
  fi
}

if [ "$1" = "random" ]; then
  random_verse
elif [ "$1" = "named" ]; then
  if [ -z "$2" ]; then
    echo "Missing argument for which verse"
    exit 1
  fi
  named_verse "$2"
elif [ -z "$1" ]; then
  echo "Subcommands: random, named [reference]"
  exit 1
else
  echo "Unknown command: $1"
  exit 1
fi
